create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 16),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "public can read scores" on public.scores;
create policy "public can read scores"
on public.scores for select
to anon
using (true);

drop policy if exists "public can insert scores" on public.scores;
create policy "public can insert scores"
on public.scores for insert
to anon
with check (
  char_length(name) between 1 and 16
  and score between 0 and 100000000
);

create index if not exists scores_score_idx
on public.scores(score desc, created_at asc);

create index if not exists scores_created_idx
on public.scores(created_at desc);
