-- SPIDER JUMP: глобальный лидерборд Supabase
-- 1) Создайте проект на supabase.com
-- 2) Откройте SQL Editor и выполните этот файл целиком.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 16),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "public can read scores" on public.scores;
create policy "public can read scores"
on public.scores for select
to anon
using (true);

drop policy if exists "public can insert scores" on public.scores;
create policy "public can insert scores"
on public.scores for insert
to anon
with check (char_length(name) between 1 and 16 and score between 0 and 100000000);

-- Индекс для быстрого TOP-10.
create index if not exists scores_score_idx on public.scores(score desc, created_at asc);
